# Generated by Django 6.0.4 on 2026-04-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('image_1', models.ImageField(upload_to='banner/', verbose_name='Первое изображение')),
                ('image_2', models.ImageField(upload_to='banner/', verbose_name='Второе изображение')),
            ],
            options={
                'verbose_name': 'Баннер (Главная)',
                'verbose_name_plural': 'Баннер (Главная)',
            },
        ),
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок модуля')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, upload_to='course_features/', verbose_name='Иконка/Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'verbose_name': 'Текстовое наполнение', 'verbose_name_plural': 'Текстовое наполнение'},
        ),
        migrations.AlterModelOptions(
            name='splashlink',
            options={'ordering': ['order'], 'verbose_name': 'Ссылка на заставке', 'verbose_name_plural': 'Ссылки на заставке'},
        ),
        migrations.AlterModelOptions(
            name='storycategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория историй', 'verbose_name_plural': 'Категории историй'},
        ),
        migrations.AlterModelOptions(
            name='storyitem',
            options={'ordering': ['order'], 'verbose_name': 'Слайд истории', 'verbose_name_plural': 'Слайды историй'},
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ключ (тех.)'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='value',
            field=models.TextField(verbose_name='Значение (текст)'),
        ),
        migrations.AlterField(
            model_name='splashlink',
            name='icon_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('enter', 'Вход (Кнопка входа)')], default='telegram', max_length=20, verbose_name='Тип иконки'),
        ),
        migrations.AlterField(
            model_name='splashlink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='splashlink',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Текст ссылки'),
        ),
        migrations.AlterField(
            model_name='splashlink',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL / Ссылка'),
        ),
        migrations.AlterField(
            model_name='storycategory',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='storycategory',
            name='name',
            field=models.SlugField(unique=True, verbose_name='Техническое имя (ID)'),
        ),
        migrations.AlterField(
            model_name='storycategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='storycategory',
            name='thumbnail',
            field=models.ImageField(upload_to='stories/thumbs/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='storyitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.storycategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='storyitem',
            name='image',
            field=models.ImageField(upload_to='stories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='storyitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
