# Generated by Django 6.0.4 on 2026-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_coursefeature_alter_sitecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL / Ссылка')),
                ('icon_type', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('phone', 'Phone / WhatsApp')], default='telegram', max_length=20, verbose_name='Тип иконки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='splashlink',
            name='icon_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('enter', 'Вход (Кнопка входа)'), ('link', 'Обычная ссылка')], default='telegram', max_length=20, verbose_name='Тип иконки'),
        ),
    ]
