# Generated by Django 6.0.4 on 2026-04-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sociallink_alter_splashlink_icon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitem',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='shares',
            field=models.PositiveIntegerField(default=0, verbose_name='Пересылки'),
        ),
    ]
