# Generated by Django 6.0.4 on 2026-04-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key for the content (e.g. hero_title)', max_length=100, unique=True)),
                ('value', models.TextField(help_text='The actual text content')),
            ],
            options={
                'verbose_name': 'Matnli kontent',
                'verbose_name_plural': 'Matnli kontentlar',
            },
        ),
        migrations.CreateModel(
            name='SplashLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_type', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('enter', 'Enter')], default='enter', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Splash havolasi',
                'verbose_name_plural': 'Splash havolalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. zkvsk', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Display label, e.g. Zakvaska', max_length=100)),
                ('thumbnail', models.ImageField(help_text='Bubble image', upload_to='categories/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Galereya kategoriyasi',
                'verbose_name_plural': 'Galereya kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.storycategory')),
            ],
            options={
                'verbose_name': 'Storis rasm',
                'verbose_name_plural': 'Storis rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
